-- Extend ModuleName enum with CERTIFICATES
ALTER TABLE `DepartmentModuleAccess` MODIFY `module` ENUM('SALES', 'FINANCE_SALES', 'FINANCE_ADMIN', 'ADMIN', 'HR', 'PRODUCTION_TRAINING', 'PLACEMENTS', 'DIGITAL_MARKETING', 'CERTIFICATES') NOT NULL;
ALTER TABLE `UserModuleAccess` MODIFY `module` ENUM('SALES', 'FINANCE_SALES', 'FINANCE_ADMIN', 'ADMIN', 'HR', 'PRODUCTION_TRAINING', 'PLACEMENTS', 'DIGITAL_MARKETING', 'CERTIFICATES') NOT NULL;

-- CreateTable
CREATE TABLE `GeneratedCertificate` (
    `id` VARCHAR(191) NOT NULL,
    `type` ENUM('OD_INTERNSHIP_JOINING', 'BONAFIDE', 'INTERNSHIP_COMPLETION_SHORT', 'COURSE_COMPLETION', 'INTERNSHIP_COMPLETION') NOT NULL,
    `studentName` VARCHAR(191) NOT NULL,
    `certNo` VARCHAR(191) NOT NULL,
    `data` JSON NOT NULL,
    `issuedById` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `GeneratedCertificate_certNo_key`(`certNo`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `GeneratedCertificate` ADD CONSTRAINT `GeneratedCertificate_issuedById_fkey` FOREIGN KEY (`issuedById`) REFERENCES `Employee`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
